- name: "Install Filbeat Agent"
  hosts: 172.30.28.164
  gather_facts: no
  
  tasks:
     - name: Download Filbeat Agent msi
       win_get_url:
         url: https://d2iqp4b25oangd.cloudfront.net/Elk/Filebeat/filebeat-7.17.3-windows-x86_64.msi
         url_username: exploit
         url_password: 3MW9EYF6VqTNd6d
         dest: C:\Users\Administrator\Downloads\filebeat-7.17.3-windows-x86_64.msi
         force: yes

     - name: "Kill elk filebeat process"
       win_shell:  "taskkill /IM 'filebeat.exe' /F"
       ignore_errors: yes

     - name : install Filebeat
       win_package:
          path: C:\Users\Administrator\Downloads\filebeat-7.17.3-windows-x86_64.msi
          state: present
