- name: Start service ntp, if not started
  hosts: 172.31.25.67
  tasks:
    - name: super user
      ansible.builtin.shell:
        cmd: sudo su
    - name: Start a service with systemd
      systemd:
        name: ntp
        state: started
      become: yes
