- name: Run ps1 script in privileged mode
  hosts: 172.30.28.164
  become_method: runas

  tasks:
    - win_shell: 'Get-ChildItem -Path "C:\Users\Administrator\tmp" *.* -Recurse | Remove-Item -Force -Recurse'
      become: yes
      become_user: Administrator
