- name: Run ps1 script in privileged mode
  hosts: "{{ HostIP }}"
  become_method: runas

  tasks:
    - win_shell: |
        $paths = @("C:\Users\Administrator\tmp","C:\Users\Administrator\tmp1","C:\Users\Administrator\tmp2","C:\Users\Administrator\tmp3")
             For ($i=0; $i -lt $paths.Length; $i++) {
                Get-ChildItem -Path $paths[$i] -Recurse | Remove-Item -Force -Recurse
             }
      become: yes
     
    - name: "Restart zabbix agent"
      ansible.builtin.service:
        name: sshd
        state: restarted
        enabled: true
      become: yes

