- name: Reconfigure Queue
  hosts: "{{ HostIP }}"
  become_method: runas

  tasks:
    - win_shell: |
        cd  C:\Program Files\IP-LABEL\DFYROBOT\exe\ 
        IPLCoreServiceAdminCMD.exe type -start -id DFY_QUEUE_SCHEDULER 
      
      become: yes
      become_user: Administrator
      
    - name: "Restart zabbix agent"
      win_service:
       name: Zabbix Agent
       state: restarted
       
    - name: "Getting Event ID from zabbix API"
      debug:
        msg: "Event ID from zabbix API is : {{ EventId }}"
        
    - name: "Acknoledging the Event by AWX"
      debug:
        msg: "Event ID from zabbix API is : {{ EventId }}" 
        
    - name: 'event acknolagement'
      win_uri:
         url: 'http://172.30.19.224/zabbix/api_jsonrpc.php'
         method: POST
         body:
           jsonrpc: '2.0'
           method: event.acknowledge
           params:
              eventids: '{{ EventId }}'
              action: 6
              message: 'Problem resolved with AWX.'
           auth: 5cc4dc1948cce894436d76ea3abdb113
           id: 1
         body_format: json
         headers:
           Content-Type: application/json
      register: result
      
