- name: Starting robot manager
  hosts: "{{ HostIP }}"
  become_method: runas

  tasks:
    - win_shell: |
        cd  C:\Program Files\IP-LABEL\DFYROBOT\exe\ 
        IPLCoreServiceAdminCMD.exe type -start -id DFY_ROBOT_MANAGER 
      
      become: yes
      become_user: Administrator
      
    - name: "Restart zabbix agent"
      win_service:
       name: Zabbix Agent
       state: restarted
